import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', 'icons/*.png'],
      manifest: {
        name: 'Smart Feni',
        short_name: 'SmartFeni',
        description: 'Digital Service App for Feni City',
        theme_color: '#cc0000',
        background_color: '#efe7de',
        display: 'standalone',
        scope: '/',
        start_url: '/',
        icons: [
          // Icons will be auto-generated by the CI/CD script, 
          // but we define the structure here just in case.
          {
            src: 'icons/manifest-icon-192.png',
            sizes: '192x192',
            type: 'image/png'
          },
          {
            src: 'icons/manifest-icon-512.png',
            sizes: '512x512',
            type: 'image/png'
          }
        ]
      }
    })
  ],
})
